name: Digger PR flow

on:
  pull_request:
    branches: [ "main" ]
    types: [ closed, opened, synchronize, reopened ]
  issue_comment:
    types: [created]
  workflow_dispatch:


permissions:
  contents: write
  id-token: write
  pull-requests: write
  statuses: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: aws-actions/configure-aws-credentials@v4
        with:   
          aws-role-to-assume: arn:aws:iam::209539466991:role/github-oidc-connect
          profile: testaccount

      - uses: aws-actions/configure-aws-credentials@v4
        with:   
          aws-role-to-assume: arn:aws:iam::209539466991:role/github-oidc-connect
          profile: stagingaccount

      - name: digger run
        uses: diggerhq/digger@fix/error-reporting-swallowing-of-error
        with:
          setup-aws: true
          aws-role-to-assume: arn:aws:iam::209539466991:role/github-oidc-connect
          aws-region: us-east-1
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
